version: 2

updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "alvincrespo"
    assignees:
      - "alvincrespo"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      go-dependencies:
        patterns:
          - "github.com/spf13/*"
          - "github.com/fatih/*"
          - "golang.org/x/*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "alvincrespo"
    assignees:
      - "alvincrespo"
    commit-message:
      prefix: "ci"
      include: "scope"
