name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race ./...

      - name: Extract release notes
        id: extract-release-notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -o bin/glypto-linux-amd64 ./cmd/glypto
          GOOS=linux GOARCH=arm64 go build -o bin/glypto-linux-arm64 ./cmd/glypto
          GOOS=darwin GOARCH=amd64 go build -o bin/glypto-darwin-amd64 ./cmd/glypto
          GOOS=darwin GOARCH=arm64 go build -o bin/glypto-darwin-arm64 ./cmd/glypto
          GOOS=windows GOARCH=amd64 go build -o bin/glypto-windows-amd64.exe ./cmd/glypto
          GOOS=windows GOARCH=arm64 go build -o bin/glypto-windows-arm64.exe ./cmd/glypto

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/glypto-*
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
